### PR TITLE
Adds FreeBSD support

### PR DESCRIPTION
**Pull request by ZeWaren**
This adds support for FreeBSD, the same way the Linux support is done.

### CODE REVIEW

**Comment by bbaldino** [comment]
Thanks a lot for this!  I've been delaying merging the PR [here](https://github.com/jitsi/jitsi-sctp/pull/3) though, which ports things to CMake and worry about this making that out-of-date.  Unfortunately I just haven't had the time to go over that one yet so will have to hold off on this as well, I think.

**Comment by mstyura** [comment]
@bbaldino I think you can merge this PR as long as it relatively easy to review and looks safe and I'll update my PR as well to migrate FreeBSD support to CMake.

**Comment by ZeWaren** [comment]
Good to me!
@mstyura Let me know if you need any help with the FreeBSD particulars.

**Comment by bbaldino** [comment]
Thanks @mstyura, and thanks for your patience on the other PR!

**Pull request merged**
